trigger:
  - main

pool: 
  vmImage: ubuntu

stages:
  - stage: 
    jobs:
      - job: TerraformInit
        steps: TerraformInit
        task: TerraformInit        

                             


 