trigger:
  - main

pool: 
  vmImage: ubuntu-24.04

stages:
  - stage:
    displayName: ContinousIntegration
    jobs:
      - job:
        displayName: TerraformJob
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: '1.16.4'

        - bash: |
              echo "Terraform location:"
              which terraform

              echo "Terraform version:"
              terraform version
          displayName: Verify Terraform    
        